import { Exo_2, Play } from "next/font/google";
import "./globals.css";

const ex2 = Exo_2({
  subsets: ["latin"],
  variable: "--font-exo",
});

const play = Play({
  subsets: ["latin"],
  variable: "--font-play",
  weight: ["400", "700"],
});

export const metadata = {
  title: "LWS Xstream - Video Streaming",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`bg-color-bg text-white font-exo ${ex2.className} ${play.className}`}
      >
        <div className="container mx-auto px-4 py-4">{children}</div>
      </body>
    </html>
  );
}
