import Navbar from "@/components/navbar";
import "./globals.css";

export const metadata = {
  title: "LWS Xstream - Video Streaming",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Exo+2:wght@400;500;600;700&display=swap"
          rel="stylesheet"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Play:wght@400;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className="bg-color-bg text-white font-exo">
        <div className="container mx-auto px-4 py-4">
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  );
}
